name: fp2-haskell
version: 0.1.0.0
homepage: https://github.com/githubuser/fp2-haskell#readme
author: Author name here
maintainer: example@example.com
license: BSD-3-Clause
license-file: LICENSE
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - hashable

executables:
  fp2-haskell:
    main: Main.hs
    source-dirs: src
    dependencies:
      - fp2-haskell
      - containers
      - hashable

tests:
  fp2-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - hashable
      - fp2-haskell
      - HUnit
      - QuickCheck